name: smart_home_animation
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  fluttericon: ^2.0.0
  google_fonts: ^6.3.1
  ui_common:
    git: https://github.com/brocodev/ui_common.git
  shimmer: ^3.0.0
  rename_app: ^1.6.5
  flutter_slidable: ^4.0.1
  cloud_firestore: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
